//! Per-spawn PowerShell bootstrap file for the block hooks.
//!
//! Dot-sourced as a FILE (`-Command . '<path>'`), never typed into the PTY
//! (pwsh drops PTY-written chars during startup) and never inlined into
//! `-Command` itself (quoting limits). Regenerated on every spawn — the hook
//! token rotates — at `%LOCALAPPDATA%\Pulse\bootstrap\<id>.ps1`,
//! which inherits the user-private ACL of the data dir. Deleted with the
//! terminal.
//!
//! What the script does (PowerShell 5.1-compatible):
//!   - wraps `prompt` to emit the `pre` hook (prev command's exit code, a
//!     prompt counter, and the live cwd), the OSC 9;9 cwd report the tracker
//!     reads (moved here from the old PS_PROMPT_WRAPPER), and OSC 133;A
//!     before the rendered prompt string (the MS shell-integration pattern —
//!     coexists with PSReadLine);
//!   - wraps `PSConsoleHostReadLine` to emit OSC 133;B (prompt end — after a
//!     15ms frame drain so it lands AFTER the prompt text in the stream; the
//!     GUI composer captures the cursor cell there) before PSReadLine takes
//!     over, and the `exec` hook when a non-blank line is accepted
//!     (shell-side truncation to 2000 chars);
//!   - emits `init` once at dot-source time;
//!   - reproduces the version-faithful startup banner (PS_BANNER, #31) FIRST,
//!     once per real spawn, suppressed by `-NoLogo`-style args, so a restored
//!     terminal shows one banner instead of one per restore.
//!
//! The exit code is best-effort for cmdlet-only pipelines: PowerShell only
//! sets $LASTEXITCODE for native commands, so pure-cmdlet lines fold $? into
//! 0/1.

use std::path::PathBuf;
use uuid::Uuid;

use crate::state::data_dir;

/// Startup-banner reproduction (banner-visibility fix, pwsh half): spawning
/// with `-Command . '<bootstrap>'` makes PowerShell suppress its logo (any
/// `-Command`/`-File` implies `-NoLogo`), so hooked pwsh tabs opened to a
/// blank screen while a real terminal shows the banner. The bootstrap prints
/// it back — FIRST, before anything else, exactly once per real spawn, same
/// as cmd's honest per-spawn banner (the seam-adjacent banner dedupe in
/// serialize.rs collapses prior lifetimes' copies at restore seams).
/// Version-faithful: Windows PowerShell 5.1 prints the 2-line logo + the
/// "Install the latest PowerShell" hint (byte-verified against a real
/// interactive powershell.exe on this machine); PowerShell 7+ prints its
/// one-line `PowerShell <version>`. English-only — the real 5.1 banner is a
/// localized resource string, which is out of reach from a script; accepted.
/// Suppressed when the terminal's own args carry `-NoLogo` (see
/// `pwsh_wants_banner`) — probe terminals rely on that.
const PS_BANNER: &str = r#"if ($PSVersionTable.PSVersion.Major -ge 6) {
  [Console]::Write("PowerShell $($PSVersionTable.PSVersion)`r`n")
} else {
  [Console]::Write("Windows PowerShell`r`nCopyright (C) Microsoft Corporation. All rights reserved.`r`n`r`nInstall the latest PowerShell for new features and improvements! https://aka.ms/PSWindows`r`n`r`n")
}
"#;

/// True when a pwsh spawn should reproduce the startup banner: the user's
/// own args must not ask for `-NoLogo` (PowerShell accepts any unambiguous
/// prefix of it — `-nol`, `-nolo`, … — and `/` flags equally).
pub fn pwsh_wants_banner(args: &[String]) -> bool {
    !args.iter().any(|a| {
        let t = a.trim().to_ascii_lowercase();
        let t = match t.strip_prefix('/') {
            Some(rest) => format!("-{rest}"),
            None => t,
        };
        t.len() >= 4 && "-nologo".starts_with(t.as_str())
    })
}

/// `{TOKEN}` and `{BANNER}` are substituted at generation time.
const TEMPLATE: &str = r#"# generated by Pulse; token rotates every spawn
{BANNER}$script:TCTok = '{TOKEN}'
$script:TCN = [uint32]0
function script:TCEmit([string]$verb, $obj) {
  $json = $obj | ConvertTo-Json -Compress
  $hex  = -join ([Text.Encoding]::UTF8.GetBytes($json) | ForEach-Object { $_.ToString('x2') })
  [Console]::Write([char]27 + ']7717;' + $script:TCTok + ';' + $verb + ';' + $hex + [char]7)
}
$script:TCPrevPrompt = $function:prompt
function global:prompt {
  $q = $?; $lec = $global:LASTEXITCODE
  $e = if ($null -ne $lec) { $lec } elseif ($q) { 0 } else { 1 }
  $p = $ExecutionContext.SessionState.Path.CurrentLocation.Path
  $script:TCN++
  # ConPTY frame-flush race: conhost renders TEXT on an async frame but
  # passes OSC/CSI writes through the pipe immediately, so the pre hook
  # emitted right after a command's output can arrive BEFORE that output in
  # the stream — the recorded end_off would then exclude the very bytes it
  # must bracket (probe blocks_text caught real output loss). A buffer-info
  # query does NOT flush the frame on this conhost (tested); a short sleep
  # lets the pending frame drain first. Prompt-render latency only — the
  # exec hook stays sleep-free (it would delay every command's start, and
  # the GUI's anchor capture tolerates accept-echo skew by design).
  Start-Sleep -Milliseconds 15
  TCEmit 'pre' @{ e = $e; n = $script:TCN; d = $p }
  [Console]::Write([char]27 + ']9;9;' + $p + [char]7)
  $base = if ($script:TCPrevPrompt) { & $script:TCPrevPrompt } else { 'PS ' + $p + '> ' }
  $m = [char]27; $b = [char]7
  "$m]133;A$b" + $base
}
$script:TCPrevRL = $function:PSConsoleHostReadLine
function global:PSConsoleHostReadLine {
  # 133;B (prompt end) is emitted HERE — after the host has written the
  # prompt string, just before PSReadLine takes over — NOT inline at the end
  # of prompt()'s return value: conhost passes OSCs through the ConPTY pipe
  # immediately but renders text on an async frame (the same reorder the pre
  # hook's sleep works around), so an inline 133;B would reach the stream
  # BEFORE the prompt text it terminates and the GUI would capture the
  # prompt-end cursor at the wrong cell. The sleep drains the pending text
  # frame; it delays only PSReadLine taking over — queued keystrokes sit in
  # the console input buffer meanwhile, nothing is lost.
  Start-Sleep -Milliseconds 15
  [Console]::Write([char]27 + ']133;B' + [char]7)
  $line = if ($script:TCPrevRL) { & $script:TCPrevRL }
          else { [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace, $ExecutionContext) }
  if ($line -and $line.Trim()) {
    $c = if ($line.Length -gt 2000) { $line.Substring(0,2000) } else { $line }
    TCEmit 'exec' @{ c = $c }
  }
  $line
}
TCEmit 'init' @{ v = 1; pid = $PID }
"#;

/// The bash rcfile template (P6a §3.1.2) — same OSC 7717 hex-JSON hook
/// grammar as the ps1, delivered via `wsl.exe --exec /bin/sh -c '<guard>'`
/// with `bash --rcfile <this file over /mnt>`. Load-bearing details:
///   - LOGIN-SHELL EMULATION comes FIRST: the shell this rc replaces is a
///     LOGIN shell (`wsl.exe <distro>` starts one; an interactive ssh does
///     too), but `bash -l` IGNORES --rcfile, so the rc reproduces bash's own
///     login sequence — `/etc/profile`, then the first existing of
///     ~/.bash_profile / ~/.bash_login / ~/.profile. This is what prints the
///     distro banner + MOTD (Ubuntu: /etc/profile.d/update-motd.sh) and runs
///     the user's own greeting (neofetch et al.) exactly like a raw terminal
///     — without it the WSL/ssh tab opened NEAR-EMPTY (field bug). Fallback
///     to ~/.bashrc only when NO profile file exists (a login shell would
///     source nothing, but losing the user's interactive setup helps nobody;
///     Ubuntu's stock ~/.profile sources ~/.bashrc itself, so no double
///     sourcing on the common path);
///   - `{MOTD_PRELUDE}` is empty for WSL (the distro's own profile.d prints
///     the banner) and a pam_motd emulation for ssh (`write_bashrc_remote`):
///     sshd only runs pam_motd for interactive NO-COMMAND sessions, and the
///     bootstrap rides a remote command — so the rc best-effort cats
///     /run/motd.dynamic + /etc/motd (exactly pam_motd's sources), honoring
///     ~/.hushlogin and MOTD_SHOWN, and exports MOTD_SHOWN so a profile.d
///     motd script never double-prints;
///   - `e=$?` is captured before anything else in the pre hook — any command
///     in the hook would clobber it — and `__tc_pre` goes FIRST in
///     PROMPT_COMMAND for the same reason;
///   - the 15ms pre-hook sleep is the SAME ConPTY frame-drain as the ps1's:
///     conhost passes OSCs through the pipe immediately but renders text
///     async, so a sleep-free pre can beat the command's last output rows
///     into the stream and clip end_off; the exec hook stays sleep-free;
///   - 133;A/B are wrapped into PS1 IDEMPOTENTLY EVERY PROMPT (`__tc_wrap_ps1`)
///     because git-prompt themes rebuild PS1 inside their own PROMPT_COMMAND
///     each render; 133;B rides the end of PS1 (bash has no
///     between-prompt-paint-and-readline hook), so the ~15ms wrong-cell race
///     exists here like on pwsh — `cursor_clean` is the load-bearing guard;
///   - the exec hook is a clean-room minimal bash-preexec: a DEBUG trap with
///     a one-shot latch, so exactly the FIRST simple command after a prompt
///     emits exec (pipelines fire DEBUG per stage). The latch choreography is
///     load-bearing (probe-proven on real bash): the DEBUG trap fires for the
///     `__tc_pre` CALL itself when PROMPT_COMMAND re-runs after a ^C/empty
///     Enter at an armed prompt (no user command consumed the latch), which
///     used to emit a spurious exec labeled with stale `history 1` — so the
///     handler name-guards `__tc_*` plumbing, `__tc_pre` DISARMS at its top,
///     and arming happens in `__tc_arm`, appended LAST in PROMPT_COMMAND
///     (after any user hooks, whose own commands must not fire exec either);
///   - the JSON escaper also folds \n/\r/\t to their escapes — serde_json is
///     NOT lenient about raw control chars in strings, and a bracketed-paste
///     multi-line command puts a literal newline into `history 1`;
///   - a pre-existing user DEBUG trap is REPLACED (bash allows one) — logged
///     limitation, same class as pwsh users who redefine `prompt` after ours.
///
/// `{TOKEN}` and `{RESTORE_TRAILING}` are substituted at generation time.
const BASH_TEMPLATE: &str = r#"# generated by Pulse; token rotates every spawn
{MOTD_PRELUDE}if [ -f /etc/profile ]; then . /etc/profile; fi
if [ -f ~/.bash_profile ]; then . ~/.bash_profile
elif [ -f ~/.bash_login ]; then . ~/.bash_login
elif [ -f ~/.profile ]; then . ~/.profile
elif [ -f ~/.bashrc ]; then . ~/.bashrc
fi
__TC_TOK='{TOKEN}'; __TC_N=0; __tc_at_prompt=0
__tc_emit() {
  local hex; hex=$(printf %s "$2" | od -v -An -tx1 | tr -d ' \n')
  printf '\033]7717;%s;%s;%s\007' "$__TC_TOK" "$1" "$hex"
}
__tc_json_str() {
  local s=${1//\\/\\\\}; s=${s//\"/\\\"}
  s=${s//$'\n'/\\n}; s=${s//$'\r'/\\r}; s=${s//$'\t'/\\t}
  printf %s "$s"
}
__tc_wrap_ps1() {
  case $PS1 in
    '\[\033]133;A\007\]'*) ;;
    *) PS1="\[\033]133;A\007\]${PS1}\[\033]133;B\007\]" ;;
  esac
}
__tc_pre() {
  local e=$?
  __tc_at_prompt=0
  sleep 0.015
  __TC_N=$((__TC_N+1))
  __tc_emit pre "{\"e\":$e,\"n\":$__TC_N,\"d\":\"$(__tc_json_str "$PWD")\"}"
  printf '\033]9;9;%s\007' "$PWD"
  __tc_wrap_ps1
}
__tc_arm() { __tc_at_prompt=1; }
__tc_debug() {
  case "$BASH_COMMAND" in __tc_*) return ;; esac
  [ -n "$COMP_LINE" ] && return
  [ "$__tc_at_prompt" = 1 ] || return
  __tc_at_prompt=0
  local c; c=$(HISTTIMEFORMAT= builtin history 1 2>/dev/null); c=${c#*[0-9]  }
  [ -n "$c" ] || c=$BASH_COMMAND
  c=${c:0:2000}
  __tc_emit exec "{\"c\":\"$(__tc_json_str "$c")\"}"
}
PROMPT_COMMAND="__tc_pre${PROMPT_COMMAND:+;$PROMPT_COMMAND};__tc_arm"
trap '__tc_debug' DEBUG
__tc_emit init "{\"v\":1,\"pid\":$$,\"shell\":\"bash\",\"home\":\"$(__tc_json_str "$HOME")\",\"user\":\"$(__tc_json_str "$USER")\"}"
{RESTORE_TRAILING}"#;

/// The cmd.exe hook delivery (P6b §3.3.1): a `PROMPT` environment variable
/// value, macro-expanded by cmd at EVERY prompt render — the only per-prompt
/// code execution cmd has (no readline wrapper exists; doskey can't wrap
/// arbitrary commands; AutoRun is machine-global and therefore forbidden,
/// DO-NOT #1). `$E` = ESC, `$E\` = ST, `$P` = the live path (render-time
/// macro). Stream order per prompt: 9;9 cwd → token-bearing `pre` → 133;A →
/// prompt text → 133;B — byte-order-compatible with what the BlockScanner,
/// prompt latch, and composer already consume from pwsh/bash.
///
/// Hard limits, stated honestly (D7): PROMPT macros cannot hex-encode `$P`
/// and cannot expand `%ERRORLEVEL%` at render time (env vars in the PROMPT
/// string expand ONCE, when set), so the pre payload is a CONSTANT
/// `{"e":null,"n":0}` — the token proves liveness and closes blocks; cwd
/// rides the adjacent tokenless 9;9 (substituted daemon-side from
/// Session.osc_cwd); exit codes are permanently unavailable and no exec hook
/// exists (block records come from the SubmitCommand ledger, §5.2).
/// `user_prompt` — a pre-existing customized PROMPT — is wrapped, not
/// replaced (same courtesy as the pwsh prompt wrapper); default `$P$G`.
pub fn cmd_prompt_value(token: &str, user_prompt: Option<&str>) -> String {
    let base = user_prompt
        .map(str::trim)
        .filter(|p| !p.is_empty())
        .unwrap_or("$P$G");
    // hex of the constant pre payload {"e":null,"n":0}
    let hex = crate::strip::hex_lower(br#"{"e":null,"n":0}"#);
    format!("$E]9;9;$P$E\\$E]7717;{token};pre;{hex}$E\\$E]133;A$E\\{base}$E]133;B$E\\")
}

pub(crate) fn bootstrap_dir() -> PathBuf {
    data_dir().join("bootstrap")
}

/// Deterministic per-terminal script path — referable before the file is
/// (re)generated for a spawn.
pub fn script_path(id: Uuid) -> PathBuf {
    bootstrap_dir().join(format!("{id}.ps1"))
}

/// The bash rcfile for WSL spawns (P6a): sibling of the ps1, per-family
/// extension.
pub fn script_path_bash(id: Uuid) -> PathBuf {
    bootstrap_dir().join(format!("{id}.bashrc"))
}

/// The cmd PROMPT-value file (P6b): sibling of the ps1, per-family
/// extension. Holds the generated `PROMPT` env VALUE (one line, no trailing
/// newline) — spawn() reads it and injects it via CommandBuilder.env; a
/// missing/unreadable file degrades the spawn to hookless (no PROMPT env,
/// plain working cmd). Same rotate-per-spawn / user-private-ACL /
/// delete-with-terminal lifecycle as the ps1.
pub fn script_path_cmd(id: Uuid) -> PathBuf {
    bootstrap_dir().join(format!("{id}.cmdprompt"))
}

/// Drive-letter translation of a Windows path into WSL's automount namespace:
/// `C:\Users\z\x.bashrc` → `/mnt/c/Users/z/x.bashrc` (lowercase drive,
/// backslashes→slashes). None for UNC/relative paths (untranslatable — the
/// caller degrades to a hookless spawn with a log line).
pub fn wsl_mnt_path(p: &std::path::Path) -> Option<String> {
    let s = p.to_str()?;
    let b = s.as_bytes();
    if b.len() < 3 || !b[0].is_ascii_alphabetic() || b[1] != b':' || (b[2] != b'\\' && b[2] != b'/')
    {
        return None;
    }
    let drive = (b[0] as char).to_ascii_lowercase();
    let rest = s[3..].replace('\\', "/");
    Some(format!("/mnt/{drive}/{rest}"))
}

/// POSIX single-quote a string for embedding in the bash rcfile:
/// `'` → `'\''`, everything else literal.
pub fn sh_single_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

/// Escape a string into a JSON string literal body (quotes NOT included).
fn json_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

/// Restore trailing for a WSL rcfile when a confidently-tracked inner CLI must
/// resume (P6a §7.4): cd into the POSIX cwd, then announce the resume through
/// a REAL exec hook before running it. The manual `__tc_emit exec` is what
/// gives the resumed CLI a block — no prompt has rendered yet, so the DEBUG
/// trap is unarmed — which is also what lets the daemon's hook-based tracker
/// clear `inner_cli` when that block closes (the CLI exited back to a
/// prompt). On exit the user lands at a hooked prompt (pwsh -NoExit parity).
/// Returns None only when the resume command itself can't be single-quoted
/// (never true for registry adapters) — the caller then degrades to a plain
/// cd-only trailing.
///
/// SECURITY (r3-S1): `resume` is a COMMAND and is spliced UNQUOTED — the
/// `'`-refusal below protects only the exec-hook JSON quoting, it is NOT the
/// injection defense. That defense is `tracker::safe_resume_token`, which
/// charset-validates the only attacker-influenced part (the token) at
/// capture and again in `restore_trailing`; the rest of `resume` is a
/// template constant. Do not weaken either side.
pub fn bash_restore_trailing(posix_cwd: &str, resume: &str) -> Option<String> {
    if resume.contains('\'') {
        return None;
    }
    let cd = sh_single_quote(posix_cwd);
    let json = format!("{{\"c\":\"{}\"}}", json_escape(resume));
    Some(format!(
        "cd {cd} && {{ __tc_emit exec '{json}'; {resume}; }}"
    ))
}

/// Restore trailing for the ssh one-shot rc (P6c §3.4.1/§7.4): unlike the
/// WSL form, the cd is best-effort (`2>/dev/null`, then proceed) — the remote
/// dir may have vanished between sessions and a restore must still land at a
/// working hooked prompt, with cd's failure honest in the $PWD the hooks then
/// report. The optional resume command is announced through a REAL exec hook
/// exactly like `bash_restore_trailing` (block + inner-CLI clear-on-close).
pub fn ssh_cd_trailing(posix_cwd: &str) -> String {
    format!("cd {} 2>/dev/null", sh_single_quote(posix_cwd))
}

/// cd + resume for a confidently-tracked inner CLI inside ssh. None when the
/// resume command can't be single-quoted (never true for registry adapters).
/// SECURITY: see `bash_restore_trailing` — the injection defense for the
/// unquoted `resume` is `tracker::safe_resume_token`, not the `'`-refusal.
pub fn ssh_restore_trailing(posix_cwd: &str, resume: &str) -> Option<String> {
    if resume.contains('\'') {
        return None;
    }
    let json = format!("{{\"c\":\"{}\"}}", json_escape(resume));
    Some(format!(
        "{}; {{ __tc_emit exec '{json}'; {resume}; }}",
        ssh_cd_trailing(posix_cwd)
    ))
}

/// The remote rc's self-delete (P6c §3.4.1): the bootstrap body exports
/// `TC_RC=<mktemp path>` before exec'ing bash, and the rc removes that file
/// the moment its hooks are installed — the token rests on the remote /tmp
/// only for the bootstrap window (inv. 8). `TC_RC` itself stays exported (a
/// stale path to a deleted file): harmless, and it lets the probe assert the
/// self-delete end-to-end (`[ -e "$TC_RC" ]` is false in a healthy session).
/// Placed BEFORE the restore trailing: a resumed CLI (claude) runs
/// synchronously inside the rc and would otherwise hold the token on disk for
/// the CLI's whole lifetime.
const SSH_SELF_DELETE: &str = "[ -n \"$TC_RC\" ] && rm -f -- \"$TC_RC\"\n";

/// pam_motd emulation for the ssh delivery (P6c + banner-visibility fix):
/// sshd skips pam_motd when a remote command rides the session, so the rc
/// prints what pam_motd would have — /run/motd.dynamic (update-motd's cache)
/// then /etc/motd — before the login chain runs. Honors ~/.hushlogin and an
/// inherited MOTD_SHOWN; exports MOTD_SHOWN only when something was actually
/// printed so a distro profile.d motd script (Ubuntu WSL-style) still prints
/// on hosts where the caches don't exist. Rides INSIDE the base64-delivered
/// rc, so the outer-shell charset contract does not apply to it.
const SSH_MOTD_PRELUDE: &str = "if [ -z \"$MOTD_SHOWN\" ] && [ ! -f ~/.hushlogin ] && { [ -s /run/motd.dynamic ] || [ -s /etc/motd ]; }; then\n  cat /run/motd.dynamic /etc/motd 2>/dev/null\n  export MOTD_SHOWN=tc\nfi\n";

/// (Re)write the bash rcfile for an ssh spawn: the SAME template as WSL (one
/// template, two deliveries — `[ -f ~/.bashrc ]` sources the REMOTE user's
/// bashrc by construction) plus the /tmp self-delete, and the cd trailing is
/// the caller's best-effort ssh form. spawn() reads these bytes back and
/// base64-embeds them into the remote command (`ssh_remote_command`).
pub fn write_bashrc_remote(id: Uuid, token: &str, trailing: Option<&str>) -> anyhow::Result<PathBuf> {
    std::fs::create_dir_all(bootstrap_dir())?;
    let path = script_path_bash(id);
    let tail = format!("{SSH_SELF_DELETE}{}", trailing.unwrap_or(""));
    let body = BASH_TEMPLATE
        .replace("{MOTD_PRELUDE}", SSH_MOTD_PRELUDE)
        .replace("{TOKEN}", token)
        .replace("{RESTORE_TRAILING}", &tail);
    std::fs::write(&path, body)?;
    Ok(path)
}

/// Standard base64 (RFC 4648, with padding). Hand-rolled: the only consumer
/// is the ssh bootstrap and the alphabet choice is load-bearing (every char
/// must be shell-inert inside single quotes for POSIX sh, fish, AND csh —
/// A–Z a–z 0–9 + / = all are). Round-trip pinned in tests; the probe decodes
/// through the real coreutils `base64 -d`.
pub fn base64_encode(data: &[u8]) -> String {
    const AL: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity(data.len().div_ceil(3) * 4);
    for chunk in data.chunks(3) {
        let b = [chunk[0], *chunk.get(1).unwrap_or(&0), *chunk.get(2).unwrap_or(&0)];
        let n = (u32::from(b[0]) << 16) | (u32::from(b[1]) << 8) | u32::from(b[2]);
        out.push(AL[(n >> 18) as usize & 63] as char);
        out.push(AL[(n >> 12) as usize & 63] as char);
        out.push(if chunk.len() > 1 { AL[(n >> 6) as usize & 63] as char } else { '=' });
        out.push(if chunk.len() > 2 { AL[n as usize & 63] as char } else { '=' });
    }
    out
}

/// The POSIX body the remote `sh -c '<body>'` runs (P6c §3.4.1, D9): mktemp +
/// base64-decode the rc + exec `bash --rcfile` — with every failure degrading
/// to a WORKING shell, never a broken login:
///   - decode failed / empty (`! [ -s "$f" ]`, e.g. no base64 binary) but
///     bash exists ⇒ plain `bash -i` (hookless, user's ~/.bashrc loads
///     normally via bash's own rc path);
///   - no bash at all ⇒ `sh -i` (hookless);
///   - success ⇒ `TC_RC` exported for the rc's self-delete, then
///     `exec bash --rcfile` (rcfile sources ~/.bashrc first, template line 1).
///
/// MUST stay free of single quotes, backslashes, and `!` — the outer command
/// is single-quoted once and parsed by an UNKNOWN remote login shell (POSIX
/// sh quoting; fish treats only \' and \\ specially; csh expands `!` even
/// inside single quotes). The golden test pins these properties.
pub fn ssh_bootstrap_body(rc: &[u8]) -> String {
    let b64 = base64_encode(rc);
    format!(
        "f=$(mktemp); printf %s {b64} | base64 -d > \"$f\" 2>/dev/null; \
         if command -v bash >/dev/null 2>&1; then \
         if [ -s \"$f\" ]; then export TC_RC=\"$f\"; exec bash --rcfile \"$f\" -i; fi; \
         rm -f -- \"$f\"; exec bash -i; fi; \
         rm -f -- \"$f\"; exec sh -i"
    )
}

/// The ONE argv element appended after the ssh destination: `sh -c '<body>'`.
/// The remote login shell — whatever it is — sees a single simple command
/// (valid in every shell family); everything interesting is POSIX inside sh.
pub fn ssh_remote_command(rc: &[u8]) -> String {
    let body = ssh_bootstrap_body(rc);
    debug_assert!(
        !body.contains('\'') && !body.contains('!') && !body.contains('\\'),
        "remote body must survive any login shell's single-quoting"
    );
    format!("sh -c '{body}'")
}

/// Mint a fresh 16-lowercase-hex-char session token (random u64).
pub fn mint_token() -> String {
    let b = Uuid::new_v4();
    let v = u64::from_le_bytes(b.as_bytes()[..8].try_into().unwrap());
    format!("{v:016x}")
}

/// (Re)write the bootstrap script for a spawn, embedding `token`. `banner`
/// reproduces the suppressed startup logo at the top of the dot-source (see
/// `PS_BANNER`); callers pass `pwsh_wants_banner(&meta.args)`.
pub fn write_script(id: Uuid, token: &str, banner: bool) -> anyhow::Result<PathBuf> {
    std::fs::create_dir_all(bootstrap_dir())?;
    let path = script_path(id);
    let body = TEMPLATE
        .replace("{BANNER}", if banner { PS_BANNER } else { "" })
        .replace("{TOKEN}", token);
    std::fs::write(&path, body)?;
    Ok(path)
}

/// (Re)write the bash rcfile for a WSL spawn, embedding `token` and an
/// optional restore trailing (see `bash_restore_trailing`). LF line endings —
/// bash rejects CRLF constructs. Same rotate-per-spawn / user-private-ACL /
/// delete-with-terminal lifecycle as the ps1.
pub fn write_bashrc(id: Uuid, token: &str, trailing: Option<&str>) -> anyhow::Result<PathBuf> {
    std::fs::create_dir_all(bootstrap_dir())?;
    let path = script_path_bash(id);
    let body = BASH_TEMPLATE
        .replace("{MOTD_PRELUDE}", "")
        .replace("{TOKEN}", token)
        .replace("{RESTORE_TRAILING}", trailing.unwrap_or(""));
    std::fs::write(&path, body)?;
    Ok(path)
}

/// (Re)write the cmd PROMPT-value file for a spawn, embedding `token`. The
/// daemon's own `PROMPT` env (if the user customized it machine-wide) is
/// wrapped rather than replaced.
pub fn write_cmd_prompt(id: Uuid, token: &str) -> anyhow::Result<PathBuf> {
    std::fs::create_dir_all(bootstrap_dir())?;
    let path = script_path_cmd(id);
    let user = std::env::var("PROMPT").ok();
    std::fs::write(&path, cmd_prompt_value(token, user.as_deref()))?;
    Ok(path)
}

pub fn delete_script(id: Uuid) {
    let _ = std::fs::remove_file(script_path(id));
    let _ = std::fs::remove_file(script_path_bash(id));
    let _ = std::fs::remove_file(script_path_cmd(id));
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    /// U2: the automount translation — lowercase drive, slashes flipped,
    /// spaces preserved; UNC and relative paths are untranslatable.
    #[test]
    fn wsl_mnt_path_translation() {
        assert_eq!(
            wsl_mnt_path(Path::new("C:\\A B\\c.bashrc")).as_deref(),
            Some("/mnt/c/A B/c.bashrc")
        );
        assert_eq!(
            wsl_mnt_path(Path::new("d:\\x\\y")).as_deref(),
            Some("/mnt/d/x/y")
        );
        assert_eq!(wsl_mnt_path(Path::new("\\\\server\\share\\f")), None);
        assert_eq!(wsl_mnt_path(Path::new("relative\\f")), None);
        assert_eq!(wsl_mnt_path(Path::new("C:")), None);
    }

    /// U4: template/quoting goldens — token substitution, hook grammar bytes,
    /// restore trailing with an embedded single quote in the cwd.
    #[test]
    fn bash_template_goldens() {
        let body = BASH_TEMPLATE
            .replace("{MOTD_PRELUDE}", "")
            .replace("{TOKEN}", "0123456789abcdef");
        assert!(body.contains("__TC_TOK='0123456789abcdef'"));
        // Login-shell emulation (banner-visibility fix): /etc/profile first,
        // then bash's own login order — first existing of bash_profile /
        // bash_login / profile — with ~/.bashrc strictly a no-profile
        // fallback. The rc replaces a LOGIN shell; --rcfile can't be
        // combined with -l, so the chain lives here.
        let profile_at = body.find("if [ -f /etc/profile ]; then . /etc/profile; fi").unwrap();
        let chain_at = body
            .find("if [ -f ~/.bash_profile ]; then . ~/.bash_profile\nelif [ -f ~/.bash_login ]; then . ~/.bash_login\nelif [ -f ~/.profile ]; then . ~/.profile\nelif [ -f ~/.bashrc ]; then . ~/.bashrc\nfi")
            .unwrap();
        let tok_at = body.find("__TC_TOK=").unwrap();
        assert!(profile_at < chain_at && chain_at < tok_at,
            "login chain precedes hook installation");
        // The hook grammar bytes the scanner pins.
        assert!(body.contains(r"'\033]7717;%s;%s;%s\007'"));
        assert!(body.contains(r"'\033]9;9;%s\007'"));
        // Idempotent per-prompt PS1 wrap: 133;A prefix, 133;B suffix.
        assert!(body.contains(r#"PS1="\[\033]133;A\007\]${PS1}\[\033]133;B\007\]""#));
        assert!(body.contains(r"'\[\033]133;A\007\]'*"));
        // Ours-first (exit-code capture) + arm-LAST (user hooks must not
        // consume/trip the latch) PROMPT_COMMAND wrap.
        assert!(body.contains(
            "PROMPT_COMMAND=\"__tc_pre${PROMPT_COMMAND:+;$PROMPT_COMMAND};__tc_arm\""
        ));
        // One-shot DEBUG-trap latch + the own-plumbing name guard (the ^C
        // spurious-exec fix — probe wsl_composer_semantics pins it live).
        assert!(body.contains("trap '__tc_debug' DEBUG"));
        assert!(body.contains("case \"$BASH_COMMAND\" in __tc_*) return ;; esac"));
        assert!(body.contains("__tc_arm() { __tc_at_prompt=1; }"));
        // No CRLF (bash chokes on \r in constructs).
        assert!(!body.contains('\r'));
    }

    /// U4 (cmd half): the PROMPT value golden — token substitution, the
    /// constant hex pre payload, verb stream order (9;9 → pre → 133;A →
    /// base → 133;B), ST terminators throughout (PROMPT has no BEL macro),
    /// and user-PROMPT wrapping (never replacement).
    #[test]
    fn cmd_prompt_value_goldens() {
        let v = cmd_prompt_value("0123456789abcdef", None);
        assert_eq!(
            v,
            "$E]9;9;$P$E\\$E]7717;0123456789abcdef;pre;7b2265223a6e756c6c2c226e223a307d$E\\$E]133;A$E\\$P$G$E]133;B$E\\"
        );
        // The hex payload decodes to the exact lenient-schema constant.
        let hex = "7b2265223a6e756c6c2c226e223a307d";
        let json: Vec<u8> = hex
            .as_bytes()
            .chunks(2)
            .map(|p| {
                u8::from_str_radix(std::str::from_utf8(p).unwrap(), 16).unwrap()
            })
            .collect();
        assert_eq!(json, br#"{"e":null,"n":0}"#);
        // A customized user PROMPT is wrapped in place of $P$G.
        let v = cmd_prompt_value("t", Some("$D $P$G"));
        assert!(v.contains("$E]133;A$E\\$D $P$G$E]133;B$E\\"));
        assert!(!v.contains("$P$G$E]133;B$E\\$D"), "user prompt replaced, not wrapped");
        // Blank/whitespace user PROMPT falls back to the default.
        assert_eq!(cmd_prompt_value("t", Some("  ")), cmd_prompt_value("t", None));
        // No literal ESC/BEL bytes — everything rides $E macros.
        assert!(!v.contains('\x1b') && !v.contains('\x07'));
    }

    /// What conhost renders from that PROMPT (macros expanded) parses into
    /// exactly the hook events the daemon consumes: a tokenful `pre` with
    /// e=None/n=0/empty cwd (the osc_cwd substitution's trigger) and the
    /// tokenless 133;B prompt-end — and NO exec, ever.
    #[test]
    fn cmd_prompt_rendered_stream_parses() {
        use crate::daemon::blocks::{BlockScanner, HookVerb};
        let v = cmd_prompt_value("0123456789abcdef", None);
        // Macro expansion as cmd performs it: $E → ESC, $P → path, $G → '>',
        // $E\ therefore → ESC \ (ST).
        let rendered = v
            .replace("$E", "\x1b")
            .replace("$P", "C:\\Users\\alice")
            .replace("$G", ">");
        let mut sc = BlockScanner::new();
        let evs = sc.feed(rendered.as_bytes());
        let verbs: Vec<&HookVerb> = evs.iter().map(|e| &e.verb).collect();
        assert_eq!(verbs.len(), 2, "pre + PromptEnd only: {verbs:?}");
        assert_eq!(
            *verbs[0],
            HookVerb::Pre { exit: None, n: 0, cwd: String::new() }
        );
        assert_eq!(evs[0].token, "0123456789abcdef");
        assert_eq!(*verbs[1], HookVerb::PromptEnd);
        // The 9;9 stays a foreign OSC to the block scanner (the session's
        // OscScanner owns it) and 133;A stays ignored.
    }

    /// U4 (ssh half): base64 vectors (RFC 4648 — the remote coreutils
    /// `base64 -d` must accept our bytes verbatim; the probe proves it live).
    #[test]
    fn base64_vectors() {
        assert_eq!(base64_encode(b""), "");
        assert_eq!(base64_encode(b"f"), "Zg==");
        assert_eq!(base64_encode(b"fo"), "Zm8=");
        assert_eq!(base64_encode(b"foo"), "Zm9v");
        assert_eq!(base64_encode(b"foob"), "Zm9vYg==");
        assert_eq!(base64_encode(b"fooba"), "Zm9vYmE=");
        assert_eq!(base64_encode(b"foobar"), "Zm9vYmFy");
        // The alphabet is shell-inert inside single quotes everywhere.
        let all = base64_encode(&(0u8..=255).collect::<Vec<u8>>());
        assert!(all.chars().all(|c| c.is_ascii_alphanumeric() || c == '+' || c == '/' || c == '='));
    }

    /// U4 (ssh half): the remote command string — exact synthesis golden,
    /// single-argv `sh -c '<body>'` shape, and the fish/csh-safe outer
    /// contract (no single quotes, backslashes, or `!` inside the body).
    #[test]
    fn ssh_remote_command_golden() {
        let rc = b"echo rc";
        let cmd = ssh_remote_command(rc);
        assert_eq!(
            cmd,
            "sh -c 'f=$(mktemp); printf %s ZWNobyByYw== | base64 -d > \"$f\" 2>/dev/null; \
             if command -v bash >/dev/null 2>&1; then \
             if [ -s \"$f\" ]; then export TC_RC=\"$f\"; exec bash --rcfile \"$f\" -i; fi; \
             rm -f -- \"$f\"; exec bash -i; fi; \
             rm -f -- \"$f\"; exec sh -i'"
        );
        // Outer-shell safety: exactly the two wrapping single quotes, and no
        // csh-hot or escape-hot bytes anywhere in the body.
        let body = cmd.strip_prefix("sh -c '").unwrap().strip_suffix('\'').unwrap();
        assert!(!body.contains('\'') && !body.contains('!') && !body.contains('\\'));
        // A REAL generated rc keeps those properties too (b64 + template are
        // both inert; the trailing rides INSIDE the b64, never the body).
        let full = BASH_TEMPLATE
            .replace("{MOTD_PRELUDE}", SSH_MOTD_PRELUDE)
            .replace("{TOKEN}", "0123456789abcdef")
            .replace("{RESTORE_TRAILING}", "cd '/a b' 2>/dev/null");
        let cmd = ssh_remote_command(full.as_bytes());
        let body = cmd.strip_prefix("sh -c '").unwrap().strip_suffix('\'').unwrap();
        assert!(!body.contains('\'') && !body.contains('!') && !body.contains('\\'));
    }

    /// U4 (ssh half): the remote rc — self-delete lands between the init emit
    /// and the restore trailing (token leaves /tmp before any resumed CLI
    /// starts), and the ssh trailing forms (best-effort cd; cd+exec-emit+
    /// resume) hit their goldens.
    #[test]
    fn ssh_rcfile_and_trailing_goldens() {
        assert_eq!(ssh_cd_trailing("/home/z"), "cd '/home/z' 2>/dev/null");
        assert_eq!(
            ssh_cd_trailing("/home/o'brien"),
            "cd '/home/o'\\''brien' 2>/dev/null"
        );
        let t = ssh_restore_trailing("/srv/proj", "claude --resume abc-123").unwrap();
        assert_eq!(
            t,
            "cd '/srv/proj' 2>/dev/null; { __tc_emit exec '{\"c\":\"claude --resume abc-123\"}'; claude --resume abc-123; }"
        );
        assert!(ssh_restore_trailing("/x", "weird 'quoted' resume").is_none());
        // Assembled rc body ordering: motd prelude → login chain → … init
        // emit → self-delete → trailing.
        let tail = format!("{SSH_SELF_DELETE}{t}");
        let body = BASH_TEMPLATE
            .replace("{MOTD_PRELUDE}", SSH_MOTD_PRELUDE)
            .replace("{TOKEN}", "t")
            .replace("{RESTORE_TRAILING}", &tail);
        let motd_at = body.find("cat /run/motd.dynamic /etc/motd").unwrap();
        let profile_at = body.find(". /etc/profile").unwrap();
        let init_at = body.find("__tc_emit init").unwrap();
        let del_at = body.find("rm -f -- \"$TC_RC\"").unwrap();
        let trail_at = body.find("cd '/srv/proj'").unwrap();
        assert!(motd_at < profile_at && profile_at < init_at);
        assert!(init_at < del_at && del_at < trail_at);
        assert!(!body.contains('\r'));
        // pam_motd emulation is gated on hushlogin + MOTD_SHOWN, and marks
        // MOTD_SHOWN so profile.d motd scripts never double-print.
        assert!(body.contains("[ ! -f ~/.hushlogin ]"));
        assert!(body.contains("export MOTD_SHOWN=tc"));
    }

    /// Banner-visibility fix (pwsh half): the banner block substitutes at the
    /// TOP of the template — before the token, hooks, and init emit — prints
    /// the byte-verified 5.1 text on the Desktop branch, and disappears
    /// entirely when the spawn opts out.
    #[test]
    fn ps_template_banner_goldens() {
        let with = TEMPLATE
            .replace("{BANNER}", PS_BANNER)
            .replace("{TOKEN}", "0123456789abcdef");
        let banner_at = with.find("Windows PowerShell`r`n").unwrap();
        let tok_at = with.find("$script:TCTok").unwrap();
        let init_at = with.find("TCEmit 'init'").unwrap();
        assert!(banner_at < tok_at && tok_at < init_at, "banner precedes hooks");
        // The exact 5.1 text a real interactive powershell.exe prints
        // (captured on this machine): logo, copyright, blank, hint, blank.
        assert!(with.contains(
            "Windows PowerShell`r`nCopyright (C) Microsoft Corporation. All rights reserved.`r`n`r`nInstall the latest PowerShell for new features and improvements! https://aka.ms/PSWindows`r`n`r`n"
        ));
        // Core prints its one-line version banner instead.
        assert!(with.contains("PowerShell $($PSVersionTable.PSVersion)`r`n"));
        // Opt-out leaves no banner residue.
        let without = TEMPLATE
            .replace("{BANNER}", "")
            .replace("{TOKEN}", "0123456789abcdef");
        assert!(!without.contains("Windows PowerShell"));
        assert!(without.starts_with("# generated by Pulse"));
    }

    /// `-NoLogo` honor: any unambiguous prefix (PowerShell's own flag
    /// matching), either flag sigil, case-insensitive; unrelated flags and
    /// the ambiguous `-no` don't suppress.
    #[test]
    fn pwsh_wants_banner_nologo_forms() {
        let f = |args: &[&str]| pwsh_wants_banner(&args.iter().map(|s| s.to_string()).collect::<Vec<_>>());
        assert!(f(&[]));
        assert!(f(&["-NoProfile"]));
        assert!(f(&["-no"])); // ambiguous prefix — pwsh itself rejects it
        assert!(!f(&["-NoLogo"]));
        assert!(!f(&["-nologo"]));
        assert!(!f(&["-nol"]));
        assert!(!f(&["/nologo"]));
        assert!(f(&["-NoExit", "-Command", ". 'x.ps1'"]));
    }

    #[test]
    fn sh_single_quote_escapes() {
        assert_eq!(sh_single_quote("/home/z"), "'/home/z'");
        assert_eq!(sh_single_quote("/a'b"), "'/a'\\''b'");
        assert_eq!(sh_single_quote(""), "''");
    }

    #[test]
    fn restore_trailing_golden() {
        let t = bash_restore_trailing("/home/o'brien/proj", "claude --resume abc-123").unwrap();
        assert_eq!(
            t,
            "cd '/home/o'\\''brien/proj' && { __tc_emit exec '{\"c\":\"claude --resume abc-123\"}'; claude --resume abc-123; }"
        );
        // A resume command with a single quote can't be embedded — degrade.
        assert!(bash_restore_trailing("/x", "weird 'quoted' resume").is_none());
        // The trailing lands verbatim in the generated file.
        let body = BASH_TEMPLATE
            .replace("{MOTD_PRELUDE}", "")
            .replace("{TOKEN}", "t")
            .replace("{RESTORE_TRAILING}", &t);
        assert!(body.ends_with(&t));
    }
}
